//! Templates for different context output formats.

/// Generate the header section.
pub fn header(project_name: &str) -> String {
    format!(
        "=== ARES PROJECT MEMORY: {} ===\n\
         Generated by ARES MemoryOS — Universal AI Memory Layer\n\
         This context restores full project understanding across AI models.\n",
        project_name
    )
}

/// Section separator.
pub fn section_header(title: &str) -> String {
    format!("\n## {}\n", title)
}

/// Format a key-value pair.
pub fn kv(key: &str, value: &str) -> String {
    format!("- **{}**: {}\n", key, value)
}

/// Format a bullet list.
pub fn bullet_list(items: &[String]) -> String {
    items.iter().map(|item| format!("  - {}\n", item)).collect()
}

/// Format a numbered list.
pub fn numbered_list(items: &[String]) -> String {
    items
        .iter()
        .enumerate()
        .map(|(i, item)| format!("  {}. {}\n", i + 1, item))
        .collect()
}

/// Format a status badge.
pub fn status_badge(status: &str) -> String {
    match status {
        "accepted" | "active" | "completed" => format!("[✓ {}]", status),
        "proposed" | "in_progress" => format!("[⟳ {}]", status),
        "rejected" | "deprecated" => format!("[✗ {}]", status),
        _ => format!("[{}]", status),
    }
}

/// Context footer.
pub fn footer() -> String {
    "\n---\nEnd of ARES Project Memory. \
     This context was auto-generated. \
     For updates, run: ARES: Generate Snapshot\n"
        .to_string()
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn header_contains_project_name() {
        let h = header("MyProject");
        assert!(h.contains("MyProject"));
        assert!(h.contains("ARES"));
    }

    #[test]
    fn status_badge_formats_correctly() {
        assert!(status_badge("accepted").contains("✓"));
        assert!(status_badge("proposed").contains("⟳"));
        assert!(status_badge("rejected").contains("✗"));
    }
}
