use ares_core::AresError;
use ares_core::ProjectId;
use ares_store::Store;
use ares_store::repositories::graph::{GraphQueryContext, SqliteGraphRepository, WorkspaceContext};
use ares_store::repositories::decision::SqliteDecisionRepository;
use std::env;
use std::fs;

pub async fn execute_overview() -> Result<(), AresError> {
    let current_dir = env::current_dir().map_err(AresError::Io)?;
    let ares_dir = current_dir.join(".ares");
    if !ares_dir.exists() {
        fs::create_dir_all(&ares_dir).map_err(AresError::Io)?;
    }

    let db_path = ares_dir.join("ares.db");
    if !db_path.exists() {
        println!("No ARES database found at {:?}. Please run `ares ingest` first.", db_path);
        return Ok(());
    }

    let store = Store::open(&db_path)?;
    let project_id_str = current_dir
        .file_name()
        .and_then(|n| n.to_str())
        .unwrap_or("project");
    let project_id = ProjectId::from(project_id_str);

    let mut overview = String::new();
    overview.push_str(&format!("# ARES System Overview: {}\n\n", project_id_str));
    overview.push_str("This document is auto-generated by ARES and provides a high-level architectural, structural, and decision summary of the repository.\n\n");

    // 1. Structure (Graph Root)
    let graph_repo = SqliteGraphRepository::new(store.clone());
    let query_context = GraphQueryContext {
        workspace: WorkspaceContext {
            workspace_path: current_dir.clone(),
            workspace_name: project_id_str.to_string(),
            repositories: vec![project_id.clone()],
        },
        repository: project_id.clone(),
        max_depth: 3,
        max_nodes: 50,
        edge_filters: vec![],
        node_filters: vec![],
        layout_hint: ares_store::repositories::graph::LayoutHint::Hierarchical,
    };

    let (nodes, _) = graph_repo.get_graph_root(&query_context).unwrap_or((vec![], vec![]));
    
    overview.push_str("## 🏗️ Structural Layout\n\n");
    if nodes.is_empty() {
        overview.push_str("No structural nodes found. Has the repository been scanned? (`ares ingest`)\n\n");
    } else {
        let mut crates = vec![];
        let mut folders = vec![];
        let mut seen = std::collections::HashSet::new();
        for node in nodes {
            let path_key = node.file_path.clone().unwrap_or_default();
            if !seen.insert(path_key) {
                continue;
            }
            match node.node_type.as_str() {
                "crate" => crates.push(node),
                "folder" => folders.push(node),
                _ => {}
            }
        }
        
        if !crates.is_empty() {
            overview.push_str("### Crates / Modules\n");
            for c in crates {
                overview.push_str(&format!("- **{}**: `{}`\n", c.label, c.file_path.clone().unwrap_or_default()));
            }
            overview.push('\n');
        }
        if !folders.is_empty() {
            overview.push_str("### Key Folders\n");
            for f in folders {
                overview.push_str(&format!("- **{}**: `{}`\n", f.label, f.file_path.clone().unwrap_or_default()));
            }
            overview.push('\n');
        }
    }

    // 2. Active Decisions
    let decision_repo = SqliteDecisionRepository::new(store.clone());
    let active_decisions = decision_repo.list(&project_id, ares_core::types::decision::DecisionFilter {
        status: Some(ares_core::DecisionStatus::Accepted),
        ..Default::default()
    }).unwrap_or_default();

    overview.push_str("## 🧠 Active Architectural Decisions\n\n");
    if active_decisions.is_empty() {
        overview.push_str("No active decisions recorded.\n\n");
    } else {
        for decision in &active_decisions {
            overview.push_str(&format!("### {}\n", decision.decision_text));
            overview.push_str(&format!("- **Reason**: {}\n", decision.reason));
            if !decision.files_impacted.is_empty() {
                overview.push_str(&format!("- **Impacts Files**: {}\n", decision.files_impacted.join(", ")));
            }
            if !decision.decided_by.is_empty() {
                overview.push_str(&format!("- **Decided By**: {}\n", decision.decided_by));
            }
            overview.push('\n');
        }
    }

    // 3. Health Score
    let mut total_nodes = 0;
    let is_graph_ok = if let Ok(conn) = store.get_conn() {
        if let Ok(mut stmt) = conn.prepare("SELECT COUNT(*) FROM graph_nodes WHERE project_id = ?1") {
            if let Ok(count) = stmt.query_row([project_id.as_str()], |row| row.get::<_, i64>(0)) {
                total_nodes = count;
                true
            } else {
                false
            }
        } else {
            false
        }
    } else {
        false
    };
    
    let has_decisions = !active_decisions.is_empty();
    let health_score = match (is_graph_ok, has_decisions) {
        (true, true) => "Excellent 🟢 (Graph is healthy, decisions are tracked)",
        (true, false) => "Good 🟡 (Graph is healthy, but no architectural decisions tracked)",
        (false, _) => "Poor 🔴 (Knowledge Graph missing or corrupted)",
    };

    overview.push_str("## 🏥 Repository Health\n\n");
    overview.push_str(&format!("- **Status**: {}\n", health_score));
    overview.push_str(&format!("- **Total Memory Nodes**: {}\n", total_nodes));
    
    let out_path = ares_dir.join("system_overview.md");
    fs::write(&out_path, overview).map_err(AresError::Io)?;

    println!("Successfully generated system overview at {:?}", out_path);
    Ok(())
}
